-- MySQL Script generated by MySQL Workbench
-- Sat May 23 20:35:57 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema project_mgt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `project_mgt` ;

-- -----------------------------------------------------
-- Schema project_mgt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project_mgt` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `project_mgt` ;

-- -----------------------------------------------------
-- Table `project_mgt`.`activity_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`activity_logs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`activity_logs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `organization_id` BIGINT NOT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  `entity_type` VARCHAR(100) NULL DEFAULT NULL,
  `entity_id` BIGINT NULL DEFAULT NULL,
  `action` VARCHAR(100) NULL DEFAULT NULL,
  `old_values` JSON NULL DEFAULT NULL,
  `new_values` JSON NULL DEFAULT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` TINYINT NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_activity_logs_organization`
    FOREIGN KEY (`organization_id`)
    REFERENCES `project_mgt`.`organizations` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_activity_logs_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `project_mgt`.`users` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_activity_logs_user` ON `project_mgt`.`activity_logs` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_activity_logs_entity` ON `project_mgt`.`activity_logs` (`entity_type` ASC, `entity_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_activity_logs_org` ON `project_mgt`.`activity_logs` (`organization_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`attachments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`attachments` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`attachments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT NOT NULL,
  `uploaded_by` BIGINT NOT NULL,
  `file_name` VARCHAR(255) NULL DEFAULT NULL,
  `file_url` TEXT NULL DEFAULT NULL,
  `mime_type` VARCHAR(100) NULL DEFAULT NULL,
  `file_size` BIGINT NULL DEFAULT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` TINYINT NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_attachments_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `project_mgt`.`tasks` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_attachments_user`
    FOREIGN KEY (`uploaded_by`)
    REFERENCES `project_mgt`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_attachments_task` ON `project_mgt`.`attachments` (`task_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_attachments_user` ON `project_mgt`.`attachments` (`uploaded_by` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`board_columns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`board_columns` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`board_columns` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `position` INT NULL DEFAULT '0',
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` TINYINT NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_board_columns_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `project_mgt`.`projects` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_board_columns_project` ON `project_mgt`.`board_columns` (`project_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`comments` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`comments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `comment` LONGTEXT NOT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comments_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `project_mgt`.`tasks` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_comments_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `project_mgt`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_comments_user` ON `project_mgt`.`comments` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_comments_task` ON `project_mgt`.`comments` (`task_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`labels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`labels` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`labels` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `organization_id` BIGINT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `color` VARCHAR(20) NULL DEFAULT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` TINYINT NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_labels_organization`
    FOREIGN KEY (`organization_id`)
    REFERENCES `project_mgt`.`organizations` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_labels_organization` ON `project_mgt`.`labels` (`organization_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`lookup_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`lookup_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`lookup_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lookup_name` VARCHAR(45) NOT NULL,
  `lookup_value` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT '1',
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`milestones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`milestones` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`milestones` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `due_date` DATE NULL DEFAULT NULL,
  `status` ENUM('pending', 'in_progress', 'completed') NULL DEFAULT 'pending',
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_milestones_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `project_mgt`.`projects` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_milestones_project` ON `project_mgt`.`milestones` (`project_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`modules` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`modules` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `icon` VARCHAR(45) NOT NULL,
  `alias` VARCHAR(45) NULL DEFAULT NULL,
  `sort_order` MEDIUMINT NOT NULL,
  `route` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`notifications` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`notifications` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `type` VARCHAR(100) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `message` TEXT NULL DEFAULT NULL,
  `is_read` TINYINT(1) NULL DEFAULT '0',
  `entity_type` VARCHAR(100) NULL DEFAULT NULL,
  `entity_id` BIGINT NULL DEFAULT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` TINYINT NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_notifications_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `project_mgt`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `idx_notifications_user` ON `project_mgt`.`notifications` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`organizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`organizations` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`organizations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(100) NULL DEFAULT NULL,
  `logo_url` TEXT NULL DEFAULT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `slug` ON `project_mgt`.`organizations` (`slug` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`privileges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`privileges` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`privileges` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`project_members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`project_members` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`project_members` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `role` ENUM('owner', 'manager', 'developer', 'tester', 'viewer') NULL DEFAULT 'developer',
  `joined_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` TINYINT NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_project_members_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `project_mgt`.`projects` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_project_members_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `project_mgt`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uk_project_member` ON `project_mgt`.`project_members` (`project_id` ASC, `user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_project_members_user` ON `project_mgt`.`project_members` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`projects` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`projects` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `organization_id` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(50) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `status` ENUM('planned', 'active', 'on_hold', 'completed', 'cancelled') NULL DEFAULT 'planned',
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_projects_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `project_mgt`.`users` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_projects_organization`
    FOREIGN KEY (`organization_id`)
    REFERENCES `project_mgt`.`organizations` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_projects_created_by` ON `project_mgt`.`projects` (`created_by` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_projects_organization` ON `project_mgt`.`projects` (`organization_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`role_privilege_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`role_privilege_mapping` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`role_privilege_mapping` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT NOT NULL,
  `privilege_id` INT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_privilege_id`
    FOREIGN KEY (`privilege_id`)
    REFERENCES `project_mgt`.`privileges` (`id`),
  CONSTRAINT `fk_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `project_mgt`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_role_id_idx` ON `project_mgt`.`role_privilege_mapping` (`role_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_privilege_id_idx` ON `project_mgt`.`role_privilege_mapping` (`privilege_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`roles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `role_alias` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT '1',
  `created_by` BIGINT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name` ON `project_mgt`.`roles` (`name` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`sprints`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`sprints` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`sprints` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `goal` TEXT NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `status` ENUM('planned', 'active', 'completed') NULL DEFAULT 'planned',
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_sprints_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `project_mgt`.`projects` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_sprints_project` ON `project_mgt`.`sprints` (`project_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`task_dependencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`task_dependencies` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`task_dependencies` (
  `task_id` BIGINT NOT NULL,
  `depends_on_task_id` BIGINT NOT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` TINYINT NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`task_id`, `depends_on_task_id`),
  CONSTRAINT `fk_task_dependencies_depends_on`
    FOREIGN KEY (`depends_on_task_id`)
    REFERENCES `project_mgt`.`tasks` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_task_dependencies_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `project_mgt`.`tasks` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_task_dependencies_depends_on` ON `project_mgt`.`task_dependencies` (`depends_on_task_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`task_labels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`task_labels` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`task_labels` (
  `task_id` BIGINT NOT NULL,
  `label_id` BIGINT NOT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` TINYINT NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`task_id`, `label_id`),
  CONSTRAINT `fk_task_labels_label`
    FOREIGN KEY (`label_id`)
    REFERENCES `project_mgt`.`labels` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_task_labels_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `project_mgt`.`tasks` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_task_labels_label` ON `project_mgt`.`task_labels` (`label_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`tasks` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`tasks` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL,
  `sprint_id` BIGINT NULL DEFAULT NULL,
  `milestone_id` BIGINT NULL DEFAULT NULL,
  `board_column_id` BIGINT NULL DEFAULT NULL,
  `parent_task_id` BIGINT NULL DEFAULT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `type` INT NULL DEFAULT NULL,
  `priority` INT NULL DEFAULT NULL,
  `status` INT NULL DEFAULT NULL,
  `assignee_id` BIGINT NULL DEFAULT NULL,
  `reporter_id` BIGINT NULL DEFAULT NULL,
  `estimated_hours` DECIMAL(10,2) NULL DEFAULT '0.00',
  `actual_hours` DECIMAL(10,2) NULL DEFAULT '0.00',
  `progress_percent` TINYINT NULL DEFAULT '0',
  `recurrence_rule` VARCHAR(255) NULL DEFAULT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `due_date` DATETIME NULL DEFAULT NULL,
  `completed_at` DATETIME NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT '0',
  `created_by` BIGINT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_by` BIGINT NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tasks_assignee`
    FOREIGN KEY (`assignee_id`)
    REFERENCES `project_mgt`.`users` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_tasks_board_column`
    FOREIGN KEY (`board_column_id`)
    REFERENCES `project_mgt`.`board_columns` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_tasks_milestone`
    FOREIGN KEY (`milestone_id`)
    REFERENCES `project_mgt`.`milestones` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_tasks_parent_task`
    FOREIGN KEY (`parent_task_id`)
    REFERENCES `project_mgt`.`tasks` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_tasks_priority`
    FOREIGN KEY (`priority`)
    REFERENCES `project_mgt`.`lookup_type` (`id`),
  CONSTRAINT `fk_tasks_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `project_mgt`.`projects` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_tasks_reporter`
    FOREIGN KEY (`reporter_id`)
    REFERENCES `project_mgt`.`users` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_tasks_sprint`
    FOREIGN KEY (`sprint_id`)
    REFERENCES `project_mgt`.`sprints` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_tasks_status`
    FOREIGN KEY (`status`)
    REFERENCES `project_mgt`.`lookup_type` (`id`),
  CONSTRAINT `fk_tasks_type`
    FOREIGN KEY (`type`)
    REFERENCES `project_mgt`.`lookup_type` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_tasks_sprint` ON `project_mgt`.`tasks` (`sprint_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_tasks_milestone` ON `project_mgt`.`tasks` (`milestone_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_tasks_board_column` ON `project_mgt`.`tasks` (`board_column_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_tasks_project` ON `project_mgt`.`tasks` (`project_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_tasks_assignee` ON `project_mgt`.`tasks` (`assignee_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_tasks_reporter` ON `project_mgt`.`tasks` (`reporter_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_tasks_status` ON `project_mgt`.`tasks` (`status` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_tasks_priority` ON `project_mgt`.`tasks` (`priority` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_tasks_due_date` ON `project_mgt`.`tasks` (`due_date` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_tasks_parent` ON `project_mgt`.`tasks` (`parent_task_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_tasks_type_idx` ON `project_mgt`.`tasks` (`type` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`time_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`time_logs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`time_logs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `started_at` DATETIME NULL DEFAULT NULL,
  `ended_at` DATETIME NULL DEFAULT NULL,
  `duration_minutes` INT NULL DEFAULT '0',
  `note` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` TINYINT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_time_logs_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `project_mgt`.`tasks` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_time_logs_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `project_mgt`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_time_logs_user` ON `project_mgt`.`time_logs` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_time_logs_task` ON `project_mgt`.`time_logs` (`task_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`user_roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`user_roles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` TINYINT NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_roles_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `project_mgt`.`roles` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_user_roles_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `project_mgt`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uk_user_role` ON `project_mgt`.`user_roles` (`user_id` ASC, `role_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `user_id_UNIQUE` ON `project_mgt`.`user_roles` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_user_roles_role` ON `project_mgt`.`user_roles` (`role_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_mgt`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_mgt`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_mgt`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `organization_id` BIGINT NOT NULL,
  `first_name` VARCHAR(100) NULL DEFAULT NULL,
  `last_name` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `avatar_url` TEXT NULL DEFAULT NULL,
  `status` ENUM('active', 'inactive', 'invited') NULL DEFAULT 'active',
  `last_login_at` DATETIME NULL DEFAULT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_organization`
    FOREIGN KEY (`organization_id`)
    REFERENCES `project_mgt`.`organizations` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email` ON `project_mgt`.`users` (`email` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_users_organization` ON `project_mgt`.`users` (`organization_id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `project_mgt`.`lookup_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `project_mgt`;
INSERT INTO `project_mgt`.`lookup_type` (`id`, `lookup_name`, `lookup_value`, `status`, `created_by`, `updated_by`, `updated_at`, `created_at`) VALUES (1, 'Task Status', 'Pending', 1, 1, 1, '2026-05-23 20:22:57', '2026-05-23 20:22:57');
INSERT INTO `project_mgt`.`lookup_type` (`id`, `lookup_name`, `lookup_value`, `status`, `created_by`, `updated_by`, `updated_at`, `created_at`) VALUES (2, 'Task Status', 'In Progress', 1, 1, 1, '2026-05-23 20:22:57', '2026-05-23 20:22:57');
INSERT INTO `project_mgt`.`lookup_type` (`id`, `lookup_name`, `lookup_value`, `status`, `created_by`, `updated_by`, `updated_at`, `created_at`) VALUES (3, 'Task Status', 'Completed', 1, 1, 1, '2026-05-23 20:22:57', '2026-05-23 20:22:57');
INSERT INTO `project_mgt`.`lookup_type` (`id`, `lookup_name`, `lookup_value`, `status`, `created_by`, `updated_by`, `updated_at`, `created_at`) VALUES (4, 'Task Status', 'Ready To Test', 1, 1, 1, '2026-05-23 20:22:57', '2026-05-23 20:22:57');
INSERT INTO `project_mgt`.`lookup_type` (`id`, `lookup_name`, `lookup_value`, `status`, `created_by`, `updated_by`, `updated_at`, `created_at`) VALUES (5, 'Task Priority', 'Low', 1, 1, 1, '2026-05-23 20:22:57', '2026-05-23 20:22:57');
INSERT INTO `project_mgt`.`lookup_type` (`id`, `lookup_name`, `lookup_value`, `status`, `created_by`, `updated_by`, `updated_at`, `created_at`) VALUES (6, 'Task Priority', 'Medium', 1, 1, 1, '2026-05-23 20:22:57', '2026-05-23 20:22:57');
INSERT INTO `project_mgt`.`lookup_type` (`id`, `lookup_name`, `lookup_value`, `status`, `created_by`, `updated_by`, `updated_at`, `created_at`) VALUES (7, 'Task Priority', 'High', 1, 1, 1, '2026-05-23 20:22:57', '2026-05-23 20:22:57');
INSERT INTO `project_mgt`.`lookup_type` (`id`, `lookup_name`, `lookup_value`, `status`, `created_by`, `updated_by`, `updated_at`, `created_at`) VALUES (8, 'Task Priority', 'Blocker', 1, 1, 1, '2026-05-23 20:22:57', '2026-05-23 20:22:57');
INSERT INTO `project_mgt`.`lookup_type` (`id`, `lookup_name`, `lookup_value`, `status`, `created_by`, `updated_by`, `updated_at`, `created_at`) VALUES (9, 'Task Type', 'Bug', 1, 1, 1, '2026-05-23 20:22:57', '2026-05-23 20:22:57');
INSERT INTO `project_mgt`.`lookup_type` (`id`, `lookup_name`, `lookup_value`, `status`, `created_by`, `updated_by`, `updated_at`, `created_at`) VALUES (10, 'Task Type', 'Enhancement', 1, 1, 1, '2026-05-23 20:22:57', '2026-05-23 20:22:57');
INSERT INTO `project_mgt`.`lookup_type` (`id`, `lookup_name`, `lookup_value`, `status`, `created_by`, `updated_by`, `updated_at`, `created_at`) VALUES (11, 'Task Status', 'Deprioritized', 1, 1, 1, '2026-05-23 20:22:57', '2026-05-23 20:22:57');

COMMIT;


-- -----------------------------------------------------
-- Data for table `project_mgt`.`modules`
-- -----------------------------------------------------
START TRANSACTION;
USE `project_mgt`;
INSERT INTO `project_mgt`.`modules` (`id`, `name`, `description`, `icon`, `alias`, `sort_order`, `route`, `status`, `created_by`, `updated_by`, `updated_at`, `created_at`) VALUES (1, 'Dashboard', 'Dashboard', 'pi pi-home', 'Dashboard', 1, '/dashboard', 1, 1, 1, '2026-05-23 20:22:57', '2026-05-23 20:22:57');
INSERT INTO `project_mgt`.`modules` (`id`, `name`, `description`, `icon`, `alias`, `sort_order`, `route`, `status`, `created_by`, `updated_by`, `updated_at`, `created_at`) VALUES (2, 'Organization', 'Organization', 'pi pi-building', 'Organization', 2, '/organization', 1, 1, 1, '2026-05-23 20:22:57', '2026-05-23 20:22:57');
INSERT INTO `project_mgt`.`modules` (`id`, `name`, `description`, `icon`, `alias`, `sort_order`, `route`, `status`, `created_by`, `updated_by`, `updated_at`, `created_at`) VALUES (3, 'Users', 'Users', 'pi pi-users', 'Users', 3, '/users', 1, 1, 1, '2026-05-23 20:22:57', '2026-05-23 20:22:57');
INSERT INTO `project_mgt`.`modules` (`id`, `name`, `description`, `icon`, `alias`, `sort_order`, `route`, `status`, `created_by`, `updated_by`, `updated_at`, `created_at`) VALUES (4, 'Projects', 'Projects', 'pi pi-briefcase', 'Projects', 4, '/projects', 1, 1, 1, '2026-05-23 20:22:57', '2026-05-23 20:22:57');
INSERT INTO `project_mgt`.`modules` (`id`, `name`, `description`, `icon`, `alias`, `sort_order`, `route`, `status`, `created_by`, `updated_by`, `updated_at`, `created_at`) VALUES (5, 'Tasks', 'Tasks', 'pi pi-check-square', 'Tasks', 5, '/tasks', 1, 1, 1, '2026-05-23 20:22:57', '2026-05-23 20:22:57');

COMMIT;


-- -----------------------------------------------------
-- Data for table `project_mgt`.`privileges`
-- -----------------------------------------------------
START TRANSACTION;
USE `project_mgt`;
INSERT INTO `project_mgt`.`privileges` (`id`, `name`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 'CREATE', 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);
INSERT INTO `project_mgt`.`privileges` (`id`, `name`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'READ', 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);
INSERT INTO `project_mgt`.`privileges` (`id`, `name`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (3, 'UPDATE', 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);
INSERT INTO `project_mgt`.`privileges` (`id`, `name`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (4, 'DELETE', 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `project_mgt`.`role_privilege_mapping`
-- -----------------------------------------------------
START TRANSACTION;
USE `project_mgt`;
INSERT INTO `project_mgt`.`role_privilege_mapping` (`id`, `role_id`, `privilege_id`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 1, 1, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);
INSERT INTO `project_mgt`.`role_privilege_mapping` (`id`, `role_id`, `privilege_id`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 1, 2, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);
INSERT INTO `project_mgt`.`role_privilege_mapping` (`id`, `role_id`, `privilege_id`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (3, 1, 3, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);
INSERT INTO `project_mgt`.`role_privilege_mapping` (`id`, `role_id`, `privilege_id`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (4, 1, 4, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);
INSERT INTO `project_mgt`.`role_privilege_mapping` (`id`, `role_id`, `privilege_id`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (5, 2, 1, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);
INSERT INTO `project_mgt`.`role_privilege_mapping` (`id`, `role_id`, `privilege_id`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (6, 2, 2, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);
INSERT INTO `project_mgt`.`role_privilege_mapping` (`id`, `role_id`, `privilege_id`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (7, 2, 3, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);
INSERT INTO `project_mgt`.`role_privilege_mapping` (`id`, `role_id`, `privilege_id`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (8, 2, 4, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);
INSERT INTO `project_mgt`.`role_privilege_mapping` (`id`, `role_id`, `privilege_id`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (9, 3, 1, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);
INSERT INTO `project_mgt`.`role_privilege_mapping` (`id`, `role_id`, `privilege_id`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (10, 3, 2, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);
INSERT INTO `project_mgt`.`role_privilege_mapping` (`id`, `role_id`, `privilege_id`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (11, 3, 3, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);
INSERT INTO `project_mgt`.`role_privilege_mapping` (`id`, `role_id`, `privilege_id`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (12, 3, 4, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);
INSERT INTO `project_mgt`.`role_privilege_mapping` (`id`, `role_id`, `privilege_id`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (13, 4, 1, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);
INSERT INTO `project_mgt`.`role_privilege_mapping` (`id`, `role_id`, `privilege_id`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (14, 4, 2, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);
INSERT INTO `project_mgt`.`role_privilege_mapping` (`id`, `role_id`, `privilege_id`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (15, 4, 3, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);
INSERT INTO `project_mgt`.`role_privilege_mapping` (`id`, `role_id`, `privilege_id`, `status`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (16, 4, 4, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `project_mgt`.`roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `project_mgt`;
INSERT INTO `project_mgt`.`roles` (`id`, `name`, `description`, `role_alias`, `status`, `created_by`, `created_at`, `updated_by`, `updated_at`) VALUES (1, 'ADMIN', 'ADMIN', 'Admin', 1, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57');
INSERT INTO `project_mgt`.`roles` (`id`, `name`, `description`, `role_alias`, `status`, `created_by`, `created_at`, `updated_by`, `updated_at`) VALUES (2, 'PROJECT_MANAGERPROJECT_MANAGER', 'PM', 'Project Manager', 1, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57');
INSERT INTO `project_mgt`.`roles` (`id`, `name`, `description`, `role_alias`, `status`, `created_by`, `created_at`, `updated_by`, `updated_at`) VALUES (3, 'BUSINESS_ANALYST', 'BA', 'Business Analyst', 1, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57');
INSERT INTO `project_mgt`.`roles` (`id`, `name`, `description`, `role_alias`, `status`, `created_by`, `created_at`, `updated_by`, `updated_at`) VALUES (4, 'DEVELOPER', 'DEV', 'Developer', 1, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57');
INSERT INTO `project_mgt`.`roles` (`id`, `name`, `description`, `role_alias`, `status`, `created_by`, `created_at`, `updated_by`, `updated_at`) VALUES (DEFAULT, 'QA', 'QA', 'QA', 1, 1, '2026-05-23 20:22:57', 1, '2026-05-23 20:22:57');

COMMIT;

